### ISSUE TITLE
Winbar as separate plugin

### ISSUE THREAD

**Issue by gegoune** [akinsho/dotfiles#11]
Hey Akin, I have managed to get your Winbar run locally and it's pretty amazing what you have accomplished, well done!

I am wondering whether you would consider breaking it into separate plugin to ease installation?

Thanks and have a lovely Monday!

**Comment by akinsho** [comment]
Thanks, @gegoune that's kind of you. So tbh I'm currently considering deprecating some of my plugins rather than actually adding more. I've found creating plugins to be way more of a time investment than I ever wanted, and it distracts a lot from other stuff I want to build in my free time and sometimes even work. So, think I'd rather keep things like this in my config from now on.

**Comment by gegoune** [comment]
Understood! And thanks for all your work, it's greatly appreciated by many, I am sure! Also thanks for sharing your dotfiles. I'll try to port/change your winbar to my needs, thought it was worth asking. All the best!
