### ISSUE TITLE
some bugs in statuscolumn.lua

### ISSUE THREAD

**Issue by xiyaowong** [akinsho/dotfiles#14]
I often refer to your configurations to keep up with the changes in neovim, and I noticed a few bugs here  :)

1. The logic here is reversed.
https://github.com/akinsho/dotfiles/blob/8206d5057dfc2a9a62f3771214dc67c6b21446f3/.config/nvim/plugin/statuscolumn.lua#L15

```lua
return fn.foldclosed(v.lnum) == -1 and fold_opened or fold_closed 
```

2. The relative line number may be 0
https://github.com/akinsho/dotfiles/blob/8206d5057dfc2a9a62f3771214dc67c6b21446f3/.config/nvim/plugin/statuscolumn.lua#L26

```lua
 local num = vim.wo[win].relativenumber and v.relnum or v.lnum

```

**Comment by akinsho** [comment]
Thanks @xiyaowong the first condition definitely is reversed 😆. I actually just don't fold that much in practice because there's a bunch of weird edge cases with folding in neovim especially using something like `nvim-ufo`.

Re. the second one this actually behaves the way I want. I don't ever want to show a relative number of `0` since this is the current line number instead the current line number should be absolute which is how it behaves. The `falsy` check behaves like vim falsy checking so `0` is false.


<img width="206" alt="image" src="https://user-images.githubusercontent.com/22454918/230322984-b6cd9e75-5fb4-4222-a34a-a80e05b31912.png">

👆🏾 this is how it appears which is what I intended

**Comment by xiyaowong** [comment]
Wow，sometimes I switch to insert mode to see the actual line number, and you provided a good method. I suddenly realized that relative line number 0 is not practical.

I learn a lot of tips from your configuration every time.🤩
