### ISSUE TITLE
Errors in highlights.lua

### ISSUE THREAD

**Issue by saifulapm** [akinsho/dotfiles#6]
When I first open Neovim I got this error.
```
E5113: Error while calling lua chunk: /Users/saiful/.config/nvim/init.lua:29: loop or previous error loading module '
as.highlights'
```
<img width="1237" alt="Screenshot 2021-07-30 at 9 52 19 PM" src="https://user-images.githubusercontent.com/3833316/127679097-a2f3e927-4392-4862-a596-9b55b0f92465.png">

This assert showing on neovim message
```
  assert(grp, 'Cannot get a highlight without specifying a group')
```

Is there any way that I can bypass error before install plugins. 
[After Installing all plugins, there is no errors.]

Sorry for my bad explanation.

Thank you

**Comment by akinsho** [comment]
@saifulapm as I mention in the README of my dotfiles. They are not intended to be forked or cloned by anyone else *but me* they are *not designed for other people's usage*. It is  better to just take bits you understand and add them to *your own config* since there will inevitably be bugs like this which you might not understand or your system is setup different to mine.

I don't want to have to talk people through how to use my config since it isn't even intended for their usage.

I'm going to close this out, apologies if any of this sounds rude it's not intended that way, I just already maintain several different plugins and don't really want my dotfiles repo to become the source of more work for me, since I could have just left it private to avoid that.
